### ISSUE TITLE
GPUImageView does throw any warning when it cant render large image

### ISSUE THREAD

**Issue by gaurav-fueled** [cats-oss/android-gpuimage#102]

**Comment by zeeshansardar61** [comment]
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
01-29 15:39:37.297 28830-30257/com.devicebee.vlogziz W/System.err:     at jp.co.cyberagent.android.gpuimage.GPUImage$LoadImageUriTask.decode(GPUImage.java:504)
01-29 15:39:37.297 28830-30257/com.devicebee.vlogziz W/System.err:     at jp.co.cyberagent.android.gpuimage.GPUImage$LoadImageTask.loadResizedImage(GPUImage.java:604)
01-29 15:39:37.297 28830-30257/com.devicebee.vlogziz W/System.err:     at jp.co.cyberagent.android.gpuimage.GPUImage$LoadImageTask.doInBackground(GPUImage.java:589)
01-29 15:39:37.297 28830-30257/com.devicebee.vlogziz W/System.err:     at jp.co.cyberagent.android.gpuimage.GPUImage$LoadImageTask.doInBackground(GPUImage.java:565)
01-29 15:39:37.297 28830-30257/com.devicebee.vlogziz W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
01-29 15:39:37.297 28830-30257/com.devicebee.vlogziz W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-29 15:39:37.297 28830-30257/com.devicebee.vlogziz W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
01-29 15:39:37.298 28830-30257/com.devicebee.vlogziz W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-29 15:39:37.298 28830-30257/com.devicebee.vlogziz W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-29 15:39:37.299 28830-30257/com.devicebee.vlogziz W/System.err:     at java.lang.Thread.run(Thread.java:762)
01-29 15:39:37.301 28830-30257/com.devicebee.vlogziz W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
01-29 15:39:37.301 28830-30257/com.devicebee.vlogziz W/System.err:     at jp.co.cyberagent.android.gpuimage.GPUImage$LoadImageUriTask.decode(GPUImage.java:504)
01-29 15:39:37.301 28830-30257/com.devicebee.vlogziz W/System.err:     at jp.co.cyberagent.android.gpuimage.GPUImage$LoadImageTask.loadResizedImage(GPUImage.java:619)
01-29 15:39:37.302 28830-30257/com.devicebee.vlogziz W/System.err:     at jp.co.cyberagent.android.gpuimage.GPUImage$LoadImageTask.doInBackground(GPUImage.java:589)
01-29 15:39:37.302 28830-30257/com.devicebee.vlogziz W/System.err:     at jp.co.cyberagent.android.gpuimage.GPUImage$LoadImageTask.doInBackground(GPUImage.java:565)
01-29 15:39:37.302 28830-30257/com.devicebee.vlogziz W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
01-29 15:39:37.302 28830-30257/com.devicebee.vlogziz W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-29 15:39:37.302 28830-30257/com.devicebee.vlogziz W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
01-29 15:39:37.302 28830-30257/com.devicebee.vlogziz W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-29 15:39:37.302 28830-30257/com.devicebee.vlogziz W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-29 15:39:37.302 28830-30257/com.devicebee.vlogziz W/System.err:     at java.lang.Thread.run(Thread.java:762)

**Comment by sokarcreative** [comment]
same as "zeeshansardar61" here
