### ISSUE TITLE
App crashes when the range changes quickly.

### ISSUE THREAD

**Issue by swcai** [cats-oss/android-gpuimage#4]
When the sample app is running, if you change the range quickly, sometimes the app will crash. I got the following adb messages:

01-06 13:35:14.462 14995 15045 E AndroidRuntime: FATAL EXCEPTION: GLThread 4239
01-06 13:35:14.462 14995 15045 E AndroidRuntime: java.util.NoSuchElementException
01-06 13:35:14.462 14995 15045 E AndroidRuntime:    at java.util.LinkedList.removeFirstImpl(LinkedList.java:689)
01-06 13:35:14.462 14995 15045 E AndroidRuntime:    at java.util.LinkedList.removeFirst(LinkedList.java:676)
01-06 13:35:14.462 14995 15045 E AndroidRuntime:    at jp.co.cyberagent.android.gpuimage.GPUImageFilter.runPendingOnDrawTasks(GPUImageFilter.java:127)
01-06 13:35:14.462 14995 15045 E AndroidRuntime:    at jp.co.cyberagent.android.gpuimage.GPUImageFilter.onDraw(GPUImageFilter.java:102)
01-06 13:35:14.462 14995 15045 E AndroidRuntime:    at jp.co.cyberagent.android.gpuimage.GPUImageFilterGroup.onDraw(GPUImageFilterGroup.java:158)
01-06 13:35:14.462 14995 15045 E AndroidRuntime:    at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(GPUImageRenderer.java:133)
01-06 13:35:14.462 14995 15045 E AndroidRuntime:    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1487)
01-06 13:35:14.462 14995 15045 E AndroidRuntime:    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1241)
01-06 13:35:14.472   744  1067 W ActivityManager:   Force finishing activity jp.co.cyberagent.android.gpuimage.sample/.activity.ActivityCamera
01-06 13:35:14.492   666 15052 I libcamera: int android::CameraHardware::aeAfAwbThread(): previewaeafawb is waiting

Looks like a synchronization issue?

**Comment by puelocesar** [comment]
Same issue on device Moto G w/4G LTE (peregrine).

I don't have the device here to debug, but it always crash user's phone when updating filter params

**Comment by srajesh529** [comment]
Hi,
is it possible to apply range for gpu image group filters?if yes,please tell me how to apply?
Thanks

**Comment by davidaik** [comment]
I'm getting the same exception ONLY SOMETIMES.

**Comment by deshan** [comment]
I am facing this error on a senwa phone. Not always say 1 time for 25 tries. Phone model Senwa V705c

**Comment by ankitbatra11** [comment]
I too face this error:

Fatal Exception: java.util.NoSuchElementException
       at java.util.LinkedList.removeFirstImpl(LinkedList.java:689)
       at java.util.LinkedList.removeFirst(LinkedList.java:676)
       at jp.co.cyberagent.android.gpuimage.GPUImageFilter.runPendingOnDrawTasks(SourceFile:134)
       at jp.co.cyberagent.android.gpuimage.GPUImageFilter.onDraw(SourceFile:106)
       at jp.co.cyberagent.android.gpuimage.GPUImageFilterGroup.onDraw(SourceFile:203)
       at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(SourceFile:120)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by mhousser** [comment]
Same here. This issue is NOT solved.

java.util.NoSuchElementException
                                                      at java.util.LinkedList.removeFirst(LinkedList.java:270)
                                                      at jp.co.cyberagent.android.gpuimage.GPUImageFilter.runPendingOnDrawTasks(GPUImageFilter.java:134)
                                                      at jp.co.cyberagent.android.gpuimage.GPUImageFilter.onDraw(GPUImageFilter.java:106)
                                                      at jp.co.cyberagent.android.gpuimage.GPUImageFilterGroup.onDraw(GPUImageFilterGroup.java:205)
                                                      at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(GPUImageRenderer.java:120)
                                                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
                                                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

**Comment by mhousser** [comment]
Seems to be timing-related when you adjust things in a Filter Group via a slider or some other control that allows for quick changes.

**Comment by asozcan** [comment]
I just created a custom filtergroup class extends from original one and override that onDraw method with try-catch. Did it solved my problem, yes it did.

**Comment by androidapkr** [comment]
@asozcan can you please share your solution so its can be easily implemented. Thanks in advance.
