### ISSUE TITLE
GPUImage dimiss image content when i turn off screen

### ISSUE THREAD

**Issue by hpuhsp** [cats-oss/android-gpuimage#427]
# Bug Reporting   
first,the GPUImage show image filter style correctly ,but 
the GPUImageView become transparent and the image content is dismissed  after i turn off screen and turn on? any good solution will be appreciated. what can i do for this?

---Detail Below---
- Device: OPPO R11s
- OS: Android 7.1.1

--Normal
<img width="479" alt="36536b1c-0eef-4602-95ef-9898632d3682" src="https://user-images.githubusercontent.com/16182229/47845782-e0f02180-de00-11e8-867d-8a278f23f660.png">

--Error
<img width="489" alt="08ab604d-3713-467a-887b-c4c9b97b50ef" src="https://user-images.githubusercontent.com/16182229/47845820-fd8c5980-de00-11e8-8035-3228b0aff048.png">

*Please add relevant labels*

**Comment by hpuhsp** [comment]
###  Other Serious Problem Attention:

applying the filter many times results to this crash~ 


`java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
        at jp.co.cyberagent.android.gpuimage.filter.GPUImageFilter.runPendingOnDrawTasks(GPUImageFilter.java:137)
        at jp.co.cyberagent.android.gpuimage.filter.GPUImageFilter.onDraw(GPUImageFilter.java:108)
        at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(GPUImageRenderer.java:122)
        at jp.co.cyberagent.android.gpuimage.GLTextureView$GLThread.guardedRun(GLTextureView.java:1412)
        at jp.co.cyberagent.android.gpuimage.GLTextureView$GLThread.run(GLTextureView.java:1142)
11-02 18:01:56.305 5125-6544/com.jiuhuar.android.debug E/XgStat: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
        at jp.co.cyberagent.android.gpuimage.filter.GPUImageFilter.runPendingOnDrawTasks(GPUImageFilter.java:137)
        at jp.co.cyberagent.android.gpuimage.filter.GPUImageFilter.onDraw(GPUImageFilter.java:108)
        at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(GPUImageRenderer.java:122)
        at jp.co.cyberagent.android.gpuimage.GLTextureView$GLThread.guardedRun(GLTextureView.java:1412)
        at jp.co.cyberagent.android.gpuimage.GLTextureView$GLThread.run(GLTextureView.java:1142)`
