### ISSUE TITLE
Rare NPE when calling getBitmapWithFilterApplied()

### ISSUE THREAD

**Issue by ubuntudroid** [cats-oss/android-gpuimage#57]
I rarely receive a NPE during execution of `GPUImage.getBitmapWithFilterApplied()`. Hoped I had fixed it with commit 0c4334686246427166a805cd1fed03d66a07b110, but the problem still persists. I've found out, that it in fact only occurs if I've no GLSurfaceView set.

Stacktrace:

```
07-08 12:17:55.843: E/AndroidRuntime(11370): java.lang.NullPointerException
07-08 12:17:55.843: E/AndroidRuntime(11370):    at jp.co.cyberagent.android.gpuimage.GPUImageFilterGroup.onDraw(GPUImageFilterGroup.java:210)
07-08 12:17:55.843: E/AndroidRuntime(11370):    at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onDrawFrame(GPUImageRenderer.java:116)
07-08 12:17:55.843: E/AndroidRuntime(11370):    at jp.co.cyberagent.android.gpuimage.PixelBuffer.getBitmap(PixelBuffer.java:121)
07-08 12:17:55.843: E/AndroidRuntime(11370):    at jp.co.cyberagent.android.gpuimage.GPUImage.getBitmapWithFilterApplied(GPUImage.java:288)
```

**Comment by Ghuizing** [comment]
I see that what Metric suggested hasn't been changed. Would it be possible to fix this bug? I can't get it to work!
